/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UninstallRouteImport } from './routes/uninstall'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as MarketplaceCreateRouteImport } from './routes/marketplace/create'
import { Route as MarketplaceCollectionsRouteImport } from './routes/marketplace/collections'
import { Route as MarketplaceAuthorsRouteImport } from './routes/marketplace/authors'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogChangelogRouteImport } from './routes/blog/changelog'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as MarketplaceCollectionCollectionRouteImport } from './routes/marketplace/collection/$collection'
import { Route as MarketplaceAuthorAuthorRouteImport } from './routes/marketplace/author/$author'
import { Route as MarketplaceCategoryIdRouteImport } from './routes/marketplace/$category/$id'
import { Route as BlogTagTagRouteImport } from './routes/blog/tag/$tag'
import { Route as BlogPagePageRouteImport } from './routes/blog/page/$page'

const UninstallRoute = UninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCreateRoute = MarketplaceCreateRouteImport.update({
  id: '/marketplace/create',
  path: '/marketplace/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCollectionsRoute = MarketplaceCollectionsRouteImport.update({
  id: '/marketplace/collections',
  path: '/marketplace/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAuthorsRoute = MarketplaceAuthorsRouteImport.update({
  id: '/marketplace/authors',
  path: '/marketplace/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const BlogChangelogRoute = BlogChangelogRouteImport.update({
  id: '/blog/changelog',
  path: '/blog/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCollectionCollectionRoute =
  MarketplaceCollectionCollectionRouteImport.update({
    id: '/marketplace/collection/$collection',
    path: '/marketplace/collection/$collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceAuthorAuthorRoute = MarketplaceAuthorAuthorRouteImport.update({
  id: '/marketplace/author/$author',
  path: '/marketplace/author/$author',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCategoryIdRoute = MarketplaceCategoryIdRouteImport.update({
  id: '/marketplace/$category/$id',
  path: '/marketplace/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/blog/tag/$tag',
  path: '/blog/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPagePageRoute = BlogPagePageRouteImport.update({
  id: '/blog/page/$page',
  path: '/blog/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/license': typeof LicenseRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uninstall': typeof UninstallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/changelog': typeof BlogChangelogRoute
  '/docs/$': typeof DocsSplatRoute
  '/marketplace/authors': typeof MarketplaceAuthorsRoute
  '/marketplace/collections': typeof MarketplaceCollectionsRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/marketplace/$category/$id': typeof MarketplaceCategoryIdRoute
  '/marketplace/author/$author': typeof MarketplaceAuthorAuthorRoute
  '/marketplace/collection/$collection': typeof MarketplaceCollectionCollectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/license': typeof LicenseRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uninstall': typeof UninstallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/changelog': typeof BlogChangelogRoute
  '/docs/$': typeof DocsSplatRoute
  '/marketplace/authors': typeof MarketplaceAuthorsRoute
  '/marketplace/collections': typeof MarketplaceCollectionsRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/marketplace/$category/$id': typeof MarketplaceCategoryIdRoute
  '/marketplace/author/$author': typeof MarketplaceAuthorAuthorRoute
  '/marketplace/collection/$collection': typeof MarketplaceCollectionCollectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/license': typeof LicenseRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uninstall': typeof UninstallRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/changelog': typeof BlogChangelogRoute
  '/docs/$': typeof DocsSplatRoute
  '/marketplace/authors': typeof MarketplaceAuthorsRoute
  '/marketplace/collections': typeof MarketplaceCollectionsRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/marketplace/$category/$id': typeof MarketplaceCategoryIdRoute
  '/marketplace/author/$author': typeof MarketplaceAuthorAuthorRoute
  '/marketplace/collection/$collection': typeof MarketplaceCollectionCollectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branding'
    | '/contact'
    | '/demo'
    | '/dmca'
    | '/docs'
    | '/download'
    | '/license'
    | '/photography'
    | '/privacy'
    | '/showcase'
    | '/sitemap.xml'
    | '/uninstall'
    | '/blog/$slug'
    | '/blog/changelog'
    | '/docs/$'
    | '/marketplace/authors'
    | '/marketplace/collections'
    | '/marketplace/create'
    | '/blog/'
    | '/docs/'
    | '/marketplace/'
    | '/blog/page/$page'
    | '/blog/tag/$tag'
    | '/marketplace/$category/$id'
    | '/marketplace/author/$author'
    | '/marketplace/collection/$collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branding'
    | '/contact'
    | '/demo'
    | '/dmca'
    | '/download'
    | '/license'
    | '/photography'
    | '/privacy'
    | '/showcase'
    | '/sitemap.xml'
    | '/uninstall'
    | '/blog/$slug'
    | '/blog/changelog'
    | '/docs/$'
    | '/marketplace/authors'
    | '/marketplace/collections'
    | '/marketplace/create'
    | '/blog'
    | '/docs'
    | '/marketplace'
    | '/blog/page/$page'
    | '/blog/tag/$tag'
    | '/marketplace/$category/$id'
    | '/marketplace/author/$author'
    | '/marketplace/collection/$collection'
  id:
    | '__root__'
    | '/'
    | '/branding'
    | '/contact'
    | '/demo'
    | '/dmca'
    | '/docs'
    | '/download'
    | '/license'
    | '/photography'
    | '/privacy'
    | '/showcase'
    | '/sitemap.xml'
    | '/uninstall'
    | '/blog/$slug'
    | '/blog/changelog'
    | '/docs/$'
    | '/marketplace/authors'
    | '/marketplace/collections'
    | '/marketplace/create'
    | '/blog/'
    | '/docs/'
    | '/marketplace/'
    | '/blog/page/$page'
    | '/blog/tag/$tag'
    | '/marketplace/$category/$id'
    | '/marketplace/author/$author'
    | '/marketplace/collection/$collection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandingRoute: typeof BrandingRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DmcaRoute: typeof DmcaRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LicenseRoute: typeof LicenseRoute
  PhotographyRoute: typeof PhotographyRoute
  PrivacyRoute: typeof PrivacyRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UninstallRoute: typeof UninstallRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogChangelogRoute: typeof BlogChangelogRoute
  MarketplaceAuthorsRoute: typeof MarketplaceAuthorsRoute
  MarketplaceCollectionsRoute: typeof MarketplaceCollectionsRoute
  MarketplaceCreateRoute: typeof MarketplaceCreateRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  BlogPagePageRoute: typeof BlogPagePageRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
  MarketplaceCategoryIdRoute: typeof MarketplaceCategoryIdRoute
  MarketplaceAuthorAuthorRoute: typeof MarketplaceAuthorAuthorRoute
  MarketplaceCollectionCollectionRoute: typeof MarketplaceCollectionCollectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uninstall': {
      id: '/uninstall'
      path: '/uninstall'
      fullPath: '/uninstall'
      preLoaderRoute: typeof UninstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/create': {
      id: '/marketplace/create'
      path: '/marketplace/create'
      fullPath: '/marketplace/create'
      preLoaderRoute: typeof MarketplaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/collections': {
      id: '/marketplace/collections'
      path: '/marketplace/collections'
      fullPath: '/marketplace/collections'
      preLoaderRoute: typeof MarketplaceCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/authors': {
      id: '/marketplace/authors'
      path: '/marketplace/authors'
      fullPath: '/marketplace/authors'
      preLoaderRoute: typeof MarketplaceAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/changelog': {
      id: '/blog/changelog'
      path: '/blog/changelog'
      fullPath: '/blog/changelog'
      preLoaderRoute: typeof BlogChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/collection/$collection': {
      id: '/marketplace/collection/$collection'
      path: '/marketplace/collection/$collection'
      fullPath: '/marketplace/collection/$collection'
      preLoaderRoute: typeof MarketplaceCollectionCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/author/$author': {
      id: '/marketplace/author/$author'
      path: '/marketplace/author/$author'
      fullPath: '/marketplace/author/$author'
      preLoaderRoute: typeof MarketplaceAuthorAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$category/$id': {
      id: '/marketplace/$category/$id'
      path: '/marketplace/$category/$id'
      fullPath: '/marketplace/$category/$id'
      preLoaderRoute: typeof MarketplaceCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page/$page': {
      id: '/blog/page/$page'
      path: '/blog/page/$page'
      fullPath: '/blog/page/$page'
      preLoaderRoute: typeof BlogPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandingRoute: BrandingRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DmcaRoute: DmcaRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LicenseRoute: LicenseRoute,
  PhotographyRoute: PhotographyRoute,
  PrivacyRoute: PrivacyRoute,
  ShowcaseRoute: ShowcaseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UninstallRoute: UninstallRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogChangelogRoute: BlogChangelogRoute,
  MarketplaceAuthorsRoute: MarketplaceAuthorsRoute,
  MarketplaceCollectionsRoute: MarketplaceCollectionsRoute,
  MarketplaceCreateRoute: MarketplaceCreateRoute,
  BlogIndexRoute: BlogIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  BlogPagePageRoute: BlogPagePageRoute,
  BlogTagTagRoute: BlogTagTagRoute,
  MarketplaceCategoryIdRoute: MarketplaceCategoryIdRoute,
  MarketplaceAuthorAuthorRoute: MarketplaceAuthorAuthorRoute,
  MarketplaceCollectionCollectionRoute: MarketplaceCollectionCollectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
